[system]
version = "0.1.0"
type = "consulta"
description = "Consulta los países del mundo"
table = "country"
limit = 10
dialect = "mysql"

[[field]]
name = "Code"
type = "char"
primary = true
length = 3

[[field]]
name = "Name"
type = "char"
length = 52

[[field]]
name = "Region"
type = "char"
length = 26

[[field]]
name = "Population"
type = "int"
conditions = [{ operator = ">", value = 1000000, condition = 'AND' }]
