version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  adminer:
    image: shyim/adminerevo:latest
    container_name: adminer
    ports:
      - "8080:8080"
    environment:
      - ADMINER_DESIGN=nette
      - ADMINER_DEFAULT_SERVER=mysql
      - ADMINER_DEFAULT_USERNAME=user
      - ADMINER_DEFAULT_PASSWORD=password
      - ADMINER_DEFAULT_DATABASE=mydatabase
      - ADMINER_PLUGINS=tinymce
    depends_on:
      - mysql

volumes:
  mysql-data: